### ISSUE TITLE
Swedish UU

### ISSUE THREAD

**Issue by phantommaxwell** [adaneslavo/MUCfVP-EECompatibilityPatch#2]
What Unit is Carolean supposed to replace?  

Modlist:
![20180515182151_1](https://user-images.githubusercontent.com/11430209/40091496-f08a3096-586c-11e8-816d-a968c25be58e.jpg)

Seems to replace both Line Infantry and Fusiliers. 
![20180515182032_1](https://user-images.githubusercontent.com/11430209/40091472-d142fdb2-586c-11e8-923f-88834bb7acab.jpg)
![20180515175937_1](https://user-images.githubusercontent.com/11430209/40091473-d168b5ac-586c-11e8-97c1-d3ceeccab935.jpg)

**Comment by adaneslavo** [comment]
Will be fixed in next version.
